/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root.route'
import { Route as moduleDataset_conversationsDatasetConversationDotrouteRouteImport } from './../../module/dataset_conversations/dataset-conversation.route'
import { Route as chatSessionGroupsDotchatSessionGroupIdDotrouteRouteImport } from './../../chat-session-groups.$chatSessionGroupId.route'
import { Route as moduleDataset_conversationsDatasetConversationDetailDotrouteRouteImport } from './../../module/dataset_conversations/dataset-conversation-detail.route'

const moduleDataset_conversationsDatasetConversationDotrouteRoute =
  moduleDataset_conversationsDatasetConversationDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const chatSessionGroupsDotchatSessionGroupIdDotrouteRoute =
  chatSessionGroupsDotchatSessionGroupIdDotrouteRouteImport.update({
    id: '/chat-session-groups/$chatSessionGroupId',
    path: '/chat-session-groups/$chatSessionGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleDataset_conversationsDatasetConversationDetailDotrouteRoute =
  moduleDataset_conversationsDatasetConversationDetailDotrouteRouteImport.update(
    {
      id: '/dataset-conversations/$datasetConversationId',
      path: '/dataset-conversations/$datasetConversationId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof moduleDataset_conversationsDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof chatSessionGroupsDotchatSessionGroupIdDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDataset_conversationsDatasetConversationDetailDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof moduleDataset_conversationsDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof chatSessionGroupsDotchatSessionGroupIdDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDataset_conversationsDatasetConversationDetailDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof moduleDataset_conversationsDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof chatSessionGroupsDotchatSessionGroupIdDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDataset_conversationsDatasetConversationDetailDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  id:
    | '__root__'
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  moduleDataset_conversationsDatasetConversationDotrouteRoute: typeof moduleDataset_conversationsDatasetConversationDotrouteRoute
  chatSessionGroupsDotchatSessionGroupIdDotrouteRoute: typeof chatSessionGroupsDotchatSessionGroupIdDotrouteRoute
  moduleDataset_conversationsDatasetConversationDetailDotrouteRoute: typeof moduleDataset_conversationsDatasetConversationDetailDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moduleDataset_conversationsDatasetConversationDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-session-groups/$chatSessionGroupId': {
      id: '/chat-session-groups/$chatSessionGroupId'
      path: '/chat-session-groups/$chatSessionGroupId'
      fullPath: '/chat-session-groups/$chatSessionGroupId'
      preLoaderRoute: typeof chatSessionGroupsDotchatSessionGroupIdDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-conversations/$datasetConversationId': {
      id: '/dataset-conversations/$datasetConversationId'
      path: '/dataset-conversations/$datasetConversationId'
      fullPath: '/dataset-conversations/$datasetConversationId'
      preLoaderRoute: typeof moduleDataset_conversationsDatasetConversationDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  moduleDataset_conversationsDatasetConversationDotrouteRoute:
    moduleDataset_conversationsDatasetConversationDotrouteRoute,
  chatSessionGroupsDotchatSessionGroupIdDotrouteRoute:
    chatSessionGroupsDotchatSessionGroupIdDotrouteRoute,
  moduleDataset_conversationsDatasetConversationDetailDotrouteRoute:
    moduleDataset_conversationsDatasetConversationDetailDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
