dataset_ids:
  - "Double_AMAT/2013/page_18.pdf"
  - "Double_BLK/2014/page_119.pdf"
  - "Double_C/2008/page_102.pdf"
  - "Double_HII/2017/page_104.pdf"
  - "Double_MRO/2015/page_18.pdf"
  - "Double_PM/2015/page_127.pdf"
  - "Double_PM/2017/page_38.pdf"
  - "Double_RSG/2016/page_144.pdf"
  - "Double_STT/2008/page_83.pdf"
  - "Single_AMT/2004/page_81.pdf-2"
  - "Single_AON/2009/page_46.pdf-3"
  - "Single_BLK/2014/page_119.pdf-1"
  - "Single_BLK/2014/page_119.pdf-4"
  - "Single_BLL/2007/page_47.pdf-1"
  - "Single_CB/2010/page_88.pdf-1"
  - "Single_CDNS/2018/page_31.pdf-1"
  - "Single_DISH/2013/page_138.pdf-3"
  - "Single_DVN/2007/page_58.pdf-3"
  - "Single_ETR/2003/page_84.pdf-2"
  - "Single_ETR/2004/page_213.pdf-4"
  - "Single_ETR/2008/page_355.pdf-4"
  - "Single_ETR/2013/page_118.pdf-4"
  - "Single_ETR/2017/page_26.pdf-4"
  - "Single_IPG/2008/page_62.pdf-1"
  - "Single_IPG/2009/page_85.pdf-3"
  - "Single_MO/2012/page_44.pdf-4"
  - "Single_MRO/2007/page_134.pdf-1"
  - "Single_UNP/2008/page_77.pdf-2"
  - "Single_UNP/2011/page_76.pdf-1"
  - "Single_UNP/2014/page_35.pdf-3"
targets:
  - "baseline:v2"
  - "baseline-tool:v2"
  - "program-of-thought:v2"
split: dev
