/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dataset-conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dataset conversations
         * @description Return dataset conversations ordered by their database identifier.
         */
        get: operations["list_dataset_conversations_dataset_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-conversations/{dataset_conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a dataset conversation
         * @description Return a dataset conversation by its database identifier.
         */
        get: operations["get_dataset_conversation_dataset_conversations__dataset_conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-conversations/{dataset_conversation_id}/chat-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List chat sessions
         * @description Return chat sessions newest first for a dataset conversation.
         */
        get: operations["list_chat_sessions_dataset_conversations__dataset_conversation_id__chat_sessions_get"];
        put?: never;
        /**
         * Create a chat session
         * @description Create and persist an empty chat session for a dataset conversation.
         */
        post: operations["create_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-conversations/{dataset_conversation_id}/chat-sessions/{chat_session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-conversations/{dataset_conversation_id}/chat-sessions/{chat_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat Session */
        get: operations["get_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__get"];
        put?: never;
        post?: never;
        /** Delete Chat Session */
        delete: operations["delete_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__delete"];
        options?: never;
        head?: never;
        /** Update Chat Session */
        patch: operations["update_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__patch"];
        trace?: never;
    };
    "/dataset-conversations/{dataset_conversation_id}/chat-sessions/{chat_session_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Agent */
        post: operations["run_agent_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMessage
         * @description An activity progress message emitted between chat messages.
         */
        ActivityMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "activity";
            /** Activitytype */
            activityType: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * AgentVariant
         * @enum {string}
         */
        AgentVariant: "direct-mini" | "calculator-mini";
        /**
         * AssistantMessage
         * @description An assistant message.
         */
        AssistantMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            /** Content */
            content?: string | null;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCall"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * AudioInputContent
         * @description An audio input content fragment.
         */
        AudioInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "audio";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BinaryInputContent
         * @description A deprecated binary payload reference in a multimodal user message.
         */
        BinaryInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Mimetype */
            mimeType: string;
            /** Id */
            id?: string | null;
            /** Url */
            url?: string | null;
            /** Data */
            data?: string | null;
            /** Filename */
            filename?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CandidateQuestionAnswer */
        CandidateQuestionAnswer: {
            /** Question */
            question: string;
            /** Answer */
            answer: string | null;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /** Id */
            id: number;
            /** Chat Session Id */
            chat_session_id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatSessionCreateRequest */
        ChatSessionCreateRequest: {
            /** @default direct-mini */
            agent_variant: components["schemas"]["AgentVariant"];
        };
        /** ChatSessionResponse */
        ChatSessionResponse: {
            /** Id */
            id: number;
            /** Dataset Conversation Id */
            dataset_conversation_id: number;
            agent_variant: components["schemas"]["AgentVariant"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Title */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChatSessionUpdateRequest */
        ChatSessionUpdateRequest: {
            /** Title */
            title: string | null;
        };
        /**
         * Context
         * @description Additional context for the agent.
         */
        Context: {
            /** Description */
            description: string;
            /** Value */
            value: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * DatasetConversationResponse
         * @description Public representation of a stored dataset_conversation.
         */
        DatasetConversationResponse: {
            /** Id */
            id: number | null;
            /** Source Id */
            source_id: string;
            /** Split */
            split: string;
            /** Pre Text */
            pre_text: string;
            /** Post Text */
            post_text: string;
            /** Num Dialogue Turns */
            num_dialogue_turns: number | null;
            /** Has Type2 Question */
            has_type2_question: boolean | null;
            /** Has Duplicate Columns */
            has_duplicate_columns: boolean | null;
            /** Has Non Numeric Values */
            has_non_numeric_values: boolean | null;
            /** Features Json */
            features_json: string;
            /** Doc Json */
            doc_json: string | null;
            /** Dialogue Json */
            dialogue_json: string;
            /** Candidate Qa */
            candidate_qa: components["schemas"]["CandidateQuestionAnswer"][];
        };
        /**
         * DeveloperMessage
         * @description A developer message.
         */
        DeveloperMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "developer";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DocumentInputContent
         * @description A document input content fragment.
         */
        DocumentInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FunctionCall
         * @description Name and arguments of a function call.
         */
        FunctionCall: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageInputContent
         * @description An image input content fragment.
         */
        ImageInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentDataSource
         * @description Inline base64-encoded source.
         */
        InputContentDataSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "data";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentUrlSource
         * @description URL-referenced source.
         */
        InputContentUrlSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ReasoningMessage
         * @description A reasoning message containing the agent's internal reasoning process.
         */
        ReasoningMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "reasoning";
            /** Content */
            content: string;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ResumeEntry
         * @description A per-interrupt response in the resume array of a RunAgentInput.
         */
        ResumeEntry: {
            /** Interruptid */
            interruptId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "cancelled";
            /** Payload */
            payload?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RunAgentInput
         * @description Input for running an agent.
         */
        RunAgentInput: {
            /** Threadid */
            threadId: string;
            /** Runid */
            runId: string;
            /** Parentrunid */
            parentRunId?: string | null;
            /** State */
            state: unknown;
            /** Messages */
            messages: (components["schemas"]["DeveloperMessage"] | components["schemas"]["SystemMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["UserMessage"] | components["schemas"]["ToolMessage"] | components["schemas"]["ActivityMessage"] | components["schemas"]["ReasoningMessage"])[];
            /** Tools */
            tools: components["schemas"]["Tool"][];
            /** Context */
            context: components["schemas"]["Context"][];
            /** Forwardedprops */
            forwardedProps: unknown;
            /** Resume */
            resume?: components["schemas"]["ResumeEntry"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SystemMessage
         * @description A system message.
         */
        SystemMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TextInputContent
         * @description A text fragment in a multimodal user message.
         */
        TextInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Tool
         * @description A tool definition.
         */
        Tool: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolCall
         * @description A tool call, modelled after OpenAI tool calls.
         */
        ToolCall: {
            /** Id */
            id: string;
            /**
             * Type
             * @default function
             * @constant
             */
            type: "function";
            function: components["schemas"]["FunctionCall"];
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolMessage
         * @description A tool result message.
         */
        ToolMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /** Content */
            content: string;
            /** Toolcallid */
            toolCallId: string;
            /** Error */
            error?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UserMessage
         * @description A user message supporting text or multimodal content.
         */
        UserMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            /** Content */
            content: string | (components["schemas"]["TextInputContent"] | components["schemas"]["ImageInputContent"] | components["schemas"]["AudioInputContent"] | components["schemas"]["VideoInputContent"] | components["schemas"]["DocumentInputContent"] | components["schemas"]["BinaryInputContent"])[];
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoInputContent
         * @description A video input content fragment.
         */
        VideoInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_dataset_conversations_dataset_conversations_get: {
        parameters: {
            query?: {
                /** @description Number of dataset conversations to skip */
                offset?: number;
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetConversationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_conversation_dataset_conversations__dataset_conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dataset conversation database identifier */
                dataset_conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_sessions_dataset_conversations__dataset_conversation_id__chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dataset conversation database identifier */
                dataset_conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dataset conversation database identifier */
                dataset_conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ChatSessionCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_conversation_id: number;
                chat_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_conversation_id: number;
                chat_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_conversation_id: number;
                chat_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_session_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_conversation_id: number;
                chat_session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSessionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_dataset_conversations__dataset_conversation_id__chat_sessions__chat_session_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_conversation_id: number;
                chat_session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
