/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root.route'
import { Route as moduleDatasetConversationsListDatasetConversationDotrouteRouteImport } from './../../module/dataset-conversations/list/dataset-conversation.route'
import { Route as moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRouteImport } from './../../module/dataset-conversations/chat-session-groups/chat-session-group-detail.route'
import { Route as moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRouteImport } from './../../module/dataset-conversations/detail/dataset-conversation-detail.route'

const moduleDatasetConversationsListDatasetConversationDotrouteRoute =
  moduleDatasetConversationsListDatasetConversationDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute =
  moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRouteImport.update(
    {
      id: '/chat-session-groups/$chatSessionGroupId',
      path: '/chat-session-groups/$chatSessionGroupId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute =
  moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRouteImport.update(
    {
      id: '/dataset-conversations/$datasetConversationId',
      path: '/dataset-conversations/$datasetConversationId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof moduleDatasetConversationsListDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof moduleDatasetConversationsListDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof moduleDatasetConversationsListDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  id:
    | '__root__'
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  moduleDatasetConversationsListDatasetConversationDotrouteRoute: typeof moduleDatasetConversationsListDatasetConversationDotrouteRoute
  moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute: typeof moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute
  moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute: typeof moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moduleDatasetConversationsListDatasetConversationDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-session-groups/$chatSessionGroupId': {
      id: '/chat-session-groups/$chatSessionGroupId'
      path: '/chat-session-groups/$chatSessionGroupId'
      fullPath: '/chat-session-groups/$chatSessionGroupId'
      preLoaderRoute: typeof moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-conversations/$datasetConversationId': {
      id: '/dataset-conversations/$datasetConversationId'
      path: '/dataset-conversations/$datasetConversationId'
      fullPath: '/dataset-conversations/$datasetConversationId'
      preLoaderRoute: typeof moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  moduleDatasetConversationsListDatasetConversationDotrouteRoute:
    moduleDatasetConversationsListDatasetConversationDotrouteRoute,
  moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute:
    moduleDatasetConversationsChatSessionGroupsChatSessionGroupDetailDotrouteRoute,
  moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute:
    moduleDatasetConversationsDetailDatasetConversationDetailDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
