/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root.route'
import { Route as moduleDatasetDatasetConversationDotrouteRouteImport } from './../../module/dataset/dataset-conversation.route'
import { Route as moduleChatGroupChatSessionGroupDetailDotrouteRouteImport } from './../../module/chat-group/chat-session-group-detail.route'
import { Route as moduleDatasetDatasetConversationDetailDotrouteRouteImport } from './../../module/dataset/dataset-conversation-detail.route'

const moduleDatasetDatasetConversationDotrouteRoute =
  moduleDatasetDatasetConversationDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleChatGroupChatSessionGroupDetailDotrouteRoute =
  moduleChatGroupChatSessionGroupDetailDotrouteRouteImport.update({
    id: '/chat-session-groups/$chatSessionGroupId',
    path: '/chat-session-groups/$chatSessionGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleDatasetDatasetConversationDetailDotrouteRoute =
  moduleDatasetDatasetConversationDetailDotrouteRouteImport.update({
    id: '/dataset-conversations/$datasetConversationId',
    path: '/dataset-conversations/$datasetConversationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof moduleDatasetDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof moduleChatGroupChatSessionGroupDetailDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDatasetDatasetConversationDetailDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof moduleDatasetDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof moduleChatGroupChatSessionGroupDetailDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDatasetDatasetConversationDetailDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof moduleDatasetDatasetConversationDotrouteRoute
  '/chat-session-groups/$chatSessionGroupId': typeof moduleChatGroupChatSessionGroupDetailDotrouteRoute
  '/dataset-conversations/$datasetConversationId': typeof moduleDatasetDatasetConversationDetailDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  id:
    | '__root__'
    | '/'
    | '/chat-session-groups/$chatSessionGroupId'
    | '/dataset-conversations/$datasetConversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  moduleDatasetDatasetConversationDotrouteRoute: typeof moduleDatasetDatasetConversationDotrouteRoute
  moduleChatGroupChatSessionGroupDetailDotrouteRoute: typeof moduleChatGroupChatSessionGroupDetailDotrouteRoute
  moduleDatasetDatasetConversationDetailDotrouteRoute: typeof moduleDatasetDatasetConversationDetailDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moduleDatasetDatasetConversationDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-session-groups/$chatSessionGroupId': {
      id: '/chat-session-groups/$chatSessionGroupId'
      path: '/chat-session-groups/$chatSessionGroupId'
      fullPath: '/chat-session-groups/$chatSessionGroupId'
      preLoaderRoute: typeof moduleChatGroupChatSessionGroupDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-conversations/$datasetConversationId': {
      id: '/dataset-conversations/$datasetConversationId'
      path: '/dataset-conversations/$datasetConversationId'
      fullPath: '/dataset-conversations/$datasetConversationId'
      preLoaderRoute: typeof moduleDatasetDatasetConversationDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  moduleDatasetDatasetConversationDotrouteRoute:
    moduleDatasetDatasetConversationDotrouteRoute,
  moduleChatGroupChatSessionGroupDetailDotrouteRoute:
    moduleChatGroupChatSessionGroupDetailDotrouteRoute,
  moduleDatasetDatasetConversationDetailDotrouteRoute:
    moduleDatasetDatasetConversationDetailDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
